server:
  port: 8080
  address: 0.0.0.0
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Chattest
    username: kbang
    password: 0629
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update