spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/Chattest
    username: kbang
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update